name: yaib
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - black=23.3.0
  - coverage=7.2.3
  - flake8=5.0.4
  - gin-config=0.5.0
  - ignite=0.4.11
  - pytorch=2.0.1
  - lightgbm=3.3.5
  - numpy=1.24.3
  - pandas=2.0.0
  - pyarrow=11.0.0
  - pytest=7.3.1
  - scikit-learn=1.2.2
  - tensorboard=2.12.2
  - tqdm=4.64.1
  - pytorch-lightning=2.0.1
  - wandb=0.15.0
  - pip=23.1
  - scikit-optimize=0.9.0
  - einops=0.6.1
  - hydra-core=1.3
  - pip:
      - git+https://github.com/rvandewater/recipys.git
      - git+https://github.com/rvandewater/scikit-optimize.git
      - hydra-submitit-launcher==1.2.0