name: yaib
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - black=23.3.0
  - coverage=7.2.3
  - flake8=5.0.4
  - matplotlib=3.7.1
  - gin-config=0.5.0
  - ignite=0.4.11
  - pytorch=2.0.1
 # - pytorch-cuda=11.8
  - lightgbm=3.3.5
  - numpy=1.24.3
  - pandas=2.0.0
  - pyarrow=11.0.0
  - pytest=7.3.1
  - scikit-learn=1.2.2
  - tensorboard=2.12.2
  - tqdm=4.64.1
  - pytorch-lightning=2.0.3
  - torchmetrics=1.0.3
  - wandb=0.15.4
  - pip=23.1
  - einops=0.6.1
  - hydra-core=1.3
  - pip:
      - quantus==0.5.3
      - recipies==0.1.3
      # Fixed version because of NumPy incompatibility and stale development status.
      - scikit-optimize-fix==0.9.1
      - hydra-submitit-launcher==1.2.0
      - git+https://github.com/youssefmecky96/pytorchforecasting
      - git+https://github.com/youssefmecky96/captum
# Note: versioning of Pytorch might be dependent on compatible CUDA version.
# Please check yourself if your Pytorch installation supports cuda (for gpu acceleration)

